baseURL: https://recettes-recipes.github.io/blog/
disablePathToLower: true
languageCode: fr-fr
title: "Recettes and recipes"
theme: gochowdown
googleAnalytics: 
defaultcontentlanguage: en
paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: John Doe
  description: Recipes used by the Doe family
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
  hidecredits: false
  hidecopyright: false
  showNavTitle: true
  custom_css: 
    - style.css
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Category
      weight: 2
      url: /category/
    - name: Tags
      weight: 3
      url: /tags/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags